name: ClayTech-Fixed
main: cn.claycoffee.clayTech.ClayTech
version: ${project.version}
api-version: 1.20
authors: [ ClayCoffee, balugaq ]
depend: [ Slimefun, FastAsyncWorldEdit ]
softdepend: [ WorldBorder ]
commands:
  claytech:
    description: '粘土科技'
    permission: claytech.basic
permissions:
  claytech.basic:
    description: 'Basic command.'
    default: true
  claytech.checkupdate:
    description: 'check update'
    default: op
  claytech.bypasstpcheck:
    description: 'bypass planet tp check'
    default: op
